### PR TITLE
Fix: Syslog Facility and Priority for remote messages. (thanks to Mike

### PR DESCRIPTION
**Pull request by sniglet**
Miller )
Bumped: Revision to 337

Changes produce syslog events including Facility and Severity, successfully tested to comply with syslog format expected by RSA Security Analytics.

### CODE REVIEW

**Comment by binf** [comment]
Why do you want to merge my fix?

**Comment by sniglet** [comment]
It fixed a problem we've seen with two different SIEMs. (nitro and RSA
Security Analytics) They're expecting RFC compliant syslog and barnyard2
wasn't including facility and severity in the record, I figured I wasn't
the only person that'd seen that behavior.

**Comment by binf** [comment]
You can allways use my branch which is just one commit away from master.

**Comment by sniglet** [comment]
Yes, but that's a multi step build for each sensor (adding the build
environment, obtaining and building the dependencies), and I have 12 of
them. (Unless you can point me at a way to package and distribute the
updated code....I was migrating to Secuirty Onion to get away from those
kinds of headaches. ;)

**Comment by binf** [comment]
Technically you could build the binary on a single system and distribute it.
There is no new requirement or linking dependancies.

As long as all destination systems have the same processor architecture and
bit width it should go as compile and upload the binary.

**Comment by sniglet** [comment]
I'm back in the office in the morning and will give it a shot.

**Pull request merged**
